#!/usr/bin/env bash
# Per-clone setup for Searoom worktrees. Runs automatically on 'wt create'.
#
# A fresh checkout of this repository needs exactly one local setting before it
# behaves like the main checkout: commitlint hooks (see AGENTS.md). SwiftPM
# needs no other bootstrap — sources, Package.swift, and resources are tracked,
# and dist/ is generated by Scripts/build-app.sh on demand.
#
# Arguments:
#   $1 = worktree path
#   $2 = repo root
#
# Environment:
#   WT_PATH      = worktree path
#   WT_REPO_ROOT = repo root

set -euo pipefail

WT_PATH="${1:-${WT_PATH:?}}"
cd "$WT_PATH"

# Enable the tracked commitlint hooks for this clone.
git config core.hooksPath .githooks

# Fail fast on a missing toolchain, but do not warm the build here: the first
# swift build is deliberately left to the developer or agent that needs it.
if ! command -v swift >/dev/null 2>&1; then
  echo "warning: swift not found in PATH; install full Xcode or Command Line Tools" >&2
else
  echo "swift toolchain: $(swift --version 2>&1 | head -n 1)"
fi

echo "Setup complete: core.hooksPath=.githooks"
